Verzió: 10
Tesztmód: !!str True
Tanév kezdőéve: 2020
Tanar e-mail címek domain része: sulineve.sulinet.hu
Diák e-mail címek domain része: diak.sulineve.sulinet.hu
Admin: adminbot
Pedagógusok szervezeti egységének neve: Pedagógusok
Diákok szervezeti egységének neve: Diákok
Vendégek szervezeti egységének neve: Vendégek